# Generated by Django 4.2.3 on 2023-07-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='video',
            field=models.FileField(default='runString.mp4', upload_to='media'),
        ),
    ]
